# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14478296574c5c8334aed282651828d9dcf24d8969ce31b64a9b29b3c3963584afcc402aec2a1966a9221635b7d1d248b6731dbd6e9ffa309fd09256d0993ec6

test:
  secret_key_base: 63af2e657d4566ac765f7e1d270db37b13f2871d2cd360402f4065739096c297785f13a2b0ed4a2dde25dce4a66039bfb94a60c38629736ac761e8cf39bf90a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
